Enable group list for editors
FCSCOpendata/ckanext-fcscopendata pull request #65
Opened 2022-06-06 18:00 UTC by MuhammadIsmailShahzad

- Uses a function `get_dataset_group_list` to get the list of groups from the dropdown without authorizing for members
- Override the member_create function to allow the creation of the member by the theme editors

2022-06-07 05:28 UTC, sagargg requested changes

2022-06-07 05:28 UTC, sagargg commented on ckanext/fcscopendata/templates/package/group_list.html
>          {% for option in group_dropdown %}
@MuhammadIsmailShahzad it should remove the already selected group item from the dropdown option.

2022-06-08 04:02 UTC, sagargg commented
@MuhammadIsmailShahzad  Can we close this PR?  I think the change you've made already merged to the main branch and other changes are in  #61 .

2022-06-08 16:09 UTC, MuhammadIsmailShahzad commented
Closing as WONTFIX.
SEE https://github.com/FCSCOpendata/ckanext-fcscopendata/pull/65#issuecomment-1149431623 for details.

2022-06-08 16:09 UTC, closed without merging